image: ruby:3.0.1

cache:
  paths:
  - .vendor

before_script:
  - gem install bundler:2.2.20
  - bundle install --path .vendor

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
    expire_in: 366000 days
  only:
  - main
